services:
    btn.settings:
        class: Btn\SettingsBundle\Factory\SettingsFactory
        arguments:
            container: '@service_container'
            driver:    '%btn_settings.driver%'
    btn.settings.manager:
        class: Btn\SettingsBundle\Model\SettingsManager
        arguments:
            em:        '@doctrine.orm.entity_manager'
            container: '@service_container'
    btn.settings.twig.extension:
        class: Btn\SettingsBundle\Extension\SettingsTwigExtension
        arguments: [ '@btn.settings' ]
        tags:
          - { name: twig.extension }